package AppLeyes_db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import AppLeyes_db.UserORM;
import AppLeyes_db.ChatORM;

import AppLeyes_db.UserORMDao;
import AppLeyes_db.ChatORMDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userORMDaoConfig;
    private final DaoConfig chatORMDaoConfig;

    private final UserORMDao userORMDao;
    private final ChatORMDao chatORMDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userORMDaoConfig = daoConfigMap.get(UserORMDao.class).clone();
        userORMDaoConfig.initIdentityScope(type);

        chatORMDaoConfig = daoConfigMap.get(ChatORMDao.class).clone();
        chatORMDaoConfig.initIdentityScope(type);

        userORMDao = new UserORMDao(userORMDaoConfig, this);
        chatORMDao = new ChatORMDao(chatORMDaoConfig, this);

        registerDao(UserORM.class, userORMDao);
        registerDao(ChatORM.class, chatORMDao);
    }
    
    public void clear() {
        userORMDaoConfig.getIdentityScope().clear();
        chatORMDaoConfig.getIdentityScope().clear();
    }

    public UserORMDao getUserORMDao() {
        return userORMDao;
    }

    public ChatORMDao getChatORMDao() {
        return chatORMDao;
    }

}
